# Generated by Django 4.0 on 2024-07-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitment', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='ModeleDocument',
        ),
    ]
