# Generated by Django 4.0 on 2024-07-24 22:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoitment', '0007_saasentreprise_description_saasentreprise_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeledocument',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
