# Generated by Django 4.0 on 2024-07-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitment', '0008_alter_modeledocument_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeledocument',
            name='content',
            field=models.TextField(),
        ),
    ]
